if [ ! -n "$WERCKER_IKACHAN_NOTIFY_URL" ]; then
  error "Please specify url property"
  exit 1
fi

if [ ! -n "$WERCKER_IKACHAN_NOTIFY_CHANNEL" ]; then
  error "Please specify channel property"
  exit 1
fi

if [ ! -n "$WERCKER_IKACHAN_NOTIFY_PASSED_MESSAGE" ]; then
  if [ ! -n "$DEPLOY" ]; then
    export WERCKER_IKACHAN_NOTIFY_PASSED_MESSAGE="$WERCKER_APPLICATION_OWNER_NAME/$WERCKER_APPLICATION_NAME: $WERCKER_BUILD_URL build of $WERCKER_GIT_BRANCH by $WERCKER_STARTED_BY passed."
  else
    export WERCKER_IKACHAN_NOTIFY_PASSED_MESSAGE="$WERCKER_APPLICATION_OWNER_NAME/$WERCKER_APPLICATION_NAME: $WERCKER_DEPLOY_URL deploy to $WERCKER_DEPLOYTARGET_NAME by $WERCKER_STARTED_BY passed."
  fi
fi

if [ ! -n "$WERCKER_IKACHAN_NOTIFY_FAILED_MESSAGE" ]; then
  if [ ! -n "$DEPLOY" ]; then
    export WERCKER_IKACHAN_NOTIFY_FAILED_MESSAGE="$WERCKER_APPLICATION_OWNER_NAME/$WERCKER_APPLICATION_NAME: $WERCKER_BUILD_URL build of $WERCKER_GIT_BRANCH by $WERCKER_STARTED_BY failed."
  else
    export WERCKER_IKACHAN_NOTIFY_FAILED_MESSAGE="$WERCKER_APPLICATION_OWNER_NAME/$WERCKER_APPLICATION_NAME: $WERCKER_DEPLOY_URL deploy to $WERCKER_DEPLOYTARGET_NAME by $WERCKER_STARTED_BY failed."
  fi
fi

if [ "$WERCKER_RESULT" = "passed" ]; then
  export WERCKER_IKACHAN_NOTIFY_MESSAGE="$WERCKER_IKACHAN_NOTIFY_PASSED_MESSAGE"
else
  export WERCKER_IKACHAN_NOTIFY_MESSAGE="$WERCKER_IKACHAN_NOTIFY_FAILED_MESSAGE"
fi

curl $WERCKER_IKACHAN_NOTIFY_URL -X POST -d "channel=$WERCKER_IKACHAN_NOTIFY_CHANNEL" -d "message=$WERCKER_IKACHAN_NOTIFY_MESSAGE"
